// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pycdorjpxdvxodhpptog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5Y2RvcmpweGR2eG9kaHBwdG9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MTEyNjksImV4cCI6MjA3MTM4NzI2OX0.y1py1FC9HRUnlrkWbPFMpdxAjmV1lDYvkCupwChA4UM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});